---
upload_path: "/static/uploads/"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  post:
    default_front_matter_template: post
version: 0.31.1
